<?php

// Constant for Height
define("H", 0);

// Constant for Length
define("L", 1);

// Constant for Theta
define("THETA", 2);

// Constant for X coordinate
define("X", 0);

// Constant for Y coordinate
define("Y", 1);

// Convert degrees to radians
function degreesToRadians( $degrees ) {
	return $degrees * pi() / 180.0;
}

// Convert radians to degrees
function radiansToDegrees( $radians ) {
	return $radians * 180.0 / pi();
}

// Get the height value given length and theta (in degrees)
function getH( $l, $theta ) {
	return $l * sin( degreesToRadians( $theta ) );
}

// Get the length value given height and theta(in degrees)
function getL( $h, $theta ) {
	return $h / sin( degreesToRadians( $theta ) );
}

// Get the theta value (in degrees) given the height and length
function getTheta( $h, $l ) {
	return radiansToDegrees( asin( $h / $l ) );
}

// Given a point, height, length and theta (in degrees), calculates the next X,Y coordinate
function getNextPoint( $x, $y, $height, $length, $theta ) {
	// given an [x, y] coordinate, length, and theta angle, computes the next [x, y] coordiate
	$x_coord = round( $x + $length * cos( degreesToRadians( $theta ) ) );
	$y_coord = round( $y - $height );
	return array( $x_coord, $y_coord );
}

// Given data array, computes total height
function getMaxHeight( $data ) {
	return $data[0][Y];
}

// Given data array, computes total width
function getMaxWidth( $data ) {
	return $data[count($data)-1][X];
}

// Given data array, computes total height
function getTotalHeight($data) {
	$totalHeight = 0;
	
	for ($i=0; $i < count($data); $i++) {
		$totalHeight += $data[$i][H];
	}
	
	return $totalHeight;
}

// Given data array, generates array of XY coordinates
function generateXYPoints( $data ) {
	
	$originHeight = getTotalHeight( $data );
		
	// one more point than there are measurements
	$xyPoints = array();
	
	array_push($xyPoints, array(0, $originHeight));

	
	for ($i=0; $i<count($data); $i++) {
		array_push($xyPoints, getNextPoint( $xyPoints[$i][X], $xyPoints[$i][Y], $data[$i][H], $data[$i][L], $data[$i][THETA] ));
	}

	return $xyPoints;
}

function testXYPoints() {
	$testData = array(	array(3, 	5, 	36.869897645844021296855612559093),
						array(10, 	26, 22.61986494804042617294901087668),
						array(7,		25,	16.260204708311957406288774881813),
						array(5,		13,	22.61986494804042617294901087668)	);
						
	$expectedValues = array( 	array(0, 	25),
									array(4,	22),
									array(28,	12),
									array(52,	5),
									array(64,	0)	);
						
	$points = generateXYPoints( $testData );	
	
	echo "<h1>Plot Points</h1>";
	echo "<table border=1>";
	echo "<tr><th>Expected x</th><th>Expected y</th><th>Computed x</th><th>Computed y</th></tr>";
	for ($i=0; $i<count($points); $i++) {	
			echo "<tr>";
			echo "<td>" . $expectedValues[$i][X] . "</td><td>" . $expectedValues[$i][Y] . "</td>";
			echo "<td>" . $points[$i][X] . "</td><td>" . $points[$i][Y] . "</td>";
			echo "</tr>";
	}
	echo "</table>";
		
}

/********* BEGIN DATA PROCESSING FUNCTIONS **************/

define("INVALID_DATA", 9);
define("SOIL_TYPE", "soiltype");

define("BR", "\n");

/*
Given cells generated by generateCells(...), prints out the geometry file format in proper format
*/
function generateFile( $cells, $water_columns ) {
	
	echo "<pre>";
	echo count($cells) . BR;
	
	for ( $row=0; $row<count($cells); $row++ ) {
		// clear 9's
		while ( $cells[$row][0] == 9 ) {
			array_shift($cells[$row]);
		}
		
		$num_cells = count( $cells[$row] );
		$num_water = $water_columns[$row];
		$column_width = 1;
		$column_breadth = 1;
		$initial_surface_section = -0.5;
		
		echo $num_cells . " " . $num_water . " " . $column_width . " " . $column_breadth . " " . $initial_surface_section . BR;

		$text = "1 " . $cells[$row][0];
		for ( $col=1; $col<count($cells[$row]); $col++ ) {
			$text = $text . " 1 " . $cells[$row][$col];
		}
		echo $text . BR;
	}
	
	// EOF marker
	echo "0 0";
	echo "</pre>";
}

function generateWater( $width, $water ) {

	$results = array();
	
	for ( $x=0; $x < $width; $x++ ) {
		$line_seg_idx = findSegment( $x, $water );
		
		$x1 = $water[$line_seg_idx-1][X];
		$y1 = $water[$line_seg_idx-1][Y];
				
		$x2 = $water[$line_seg_idx][X];
		$y2 = $water[$line_seg_idx][Y];
		
		// calculate slope
		$slope = ( $y2 - $y1 ) / ( $x2 - $x1 );
	
		// calculate y value at the x-coordinate
		$y = round( $slope * ( $x - $x1 ) + $y1 );
	
		array_push($results, $y);
	}
	
	return $results;
}

/*
Given the profile/line segements, generates the cell data matrix

Assumes that the line segments are in right order (i.e. profile > soil1 > soil2 > soil3 > soil4

Expected soil data structure:

$soil => 	{ 	
			{x1, y1},
			{x2,y2},
			...
			"soiltype" => (0|1|2|3)
		}
*/
function generateCells( $profile, $soil1, $soil2, $soil3, $soil4 ) {

	$height = getMaxHeight( $profile );
	$width = getMaxWidth( $profile );
	
	$columns = array();
	
	$x = 0.5;
	while ( $x < $width ) {
		array_push($columns, generateColumn( $x, $height, $profile, $soil1, $soil2, $soil3, $soil4 ) );
		$x += 1.0;
	}
	
	$data = array();

	for ($col=0; $col<$height; $col++) {
		$temp = array();
		for ($row=0; $row<$width; $row++) {		
			array_push($temp, $columns[$row][$col]);
		}
		
		array_push($data, $temp);
	}
		
	return $columns;
}

/*
Given the max height, the x coord of the column, and the profile/soil line segements, generates the column data

Assumes that the line segments are in right order (i.e. profile > soil1 > soil2 > soil3 > soil4

Expected soil data structure:

$soil => 	{ 	
			{x1, y1},
			{x2,y2},
			...
			"soiltype" => (0|1|2|3)
		}
*/
function generateColumn( $x, $height, $profile, $soil1, $soil2, $soil3, $soil4 ) {
	
	$y=$height - 0.5;
	
	$column = array();
	
	while ($y > 0) {
		array_push($column, getCellValue( $x, $y, $profile, $soil1, $soil2, $soil3, $soil4 ));		
		$y -= 1.0;
	}
	
	return $column;
}

/* Given the (x,y) coordinate, the profile lines, soil lines, calculates the correct value.

Assumes that the line segments are in right order (i.e. profile > soil1 > soil2 > soil3 > soil4

Expected soil data structure:

$soil => 	{ 	
			{x1, y1},
			{x2,y2},
			...
			"soiltype" => (0|1|2|3)
		}
*/
function getCellValue( $x_coord, $y_coord, $profile, $soil1, $soil2, $soil3, $soil4 ) {
	$line_seg_idx = findSegment( $x_coord, $profile );
	
	if ( isAboveLine( $x_coord, $y_coord, 
			$profile[$line_seg_idx-1][X], $profile[$line_seg_idx-1][Y], 
			$profile[$line_seg_idx][X], $profile[$line_seg_idx][Y] ) ) {
			
		return INVALID_DATA;
	}
	
	$line_seg_idx = findSegment( $x_coord, $soil1 );
	if ( isAboveLine( $x_coord, $y_coord, 
			$soil1[$line_seg_idx-1][X], $soil1[$line_seg_idx-1][Y], 
			$soil1[$line_seg_idx][X], $soil1[$line_seg_idx][Y] ) ) {
			
		return $soil1[SOIL_TYPE];
	}
	
	$line_seg_idx = findSegment( $x_coord, $soil2 );
	if ( isAboveLine( $x_coord, $y_coord, 
			$soil2[$line_seg_idx-1][X], $soil2[$line_seg_idx-1][Y], 
			$soil2[$line_seg_idx][X], $soil2[$line_seg_idx][Y] ) ) {
			
		return $soil2[SOIL_TYPE];
	}
	
	$line_seg_idx = findSegment( $x_coord, $soil3 );
	if ( isAboveLine( $x_coord, $y_coord, 
			$soil3[$line_seg_idx-1][X], $soil3[$line_seg_idx-1][Y], 
			$soil3[$line_seg_idx][X], $soil3[$line_seg_idx][Y] ) ) {
			
		return $soil3[SOIL_TYPE];
	}
	
	$line_seg_idx = findSegment( $x_coord, $soil4 );
	if ( isAboveLine( $x_coord, $y_coord, 
			$soil4[$line_seg_idx-1][X], $soil4[$line_seg_idx-1][Y], 
			$soil4[$line_seg_idx][X], $soil4[$line_seg_idx][Y] ) ) {
			
		return $soil4[SOIL_TYPE];
	}
	
	return INVALID_DATA;
}

/*
Given an (x,y) coordinate, and the measured (x1, y1) (x2, y2) pairs from a line segment, compute
whether the given coordinate is above the line

Returns true if the y value is strictly above the line; false otherwise
*/
function isAboveLine( $x_coord, $y_coord, $x1, $y1, $x2, $y2 ) {

	// calculate slope
	$slope = ( $y2 - $y1 ) / ( $x2 - $x1 );
	
	// calculate y value at the x-coordinate
	$y = $slope * ( $x_coord - $x1 ) + $y1;
	
	return ( $y_coord > $y );
}

/*
Given an x coordinate and a contiguous set of ordered line segments, finds the
pair of line segments between which the x coordinate lies.
*/
function findSegment( $x_coord, $line_segments ) {

	for ($i=0; i < count($line_segments); $i++) {
		if ( $line_segments[$i][X] > $x_coord ) {
			return $i;
		}		
	}
}

function convertHLTtoXY( $hlt ) {
}

function testWater() {
	$water =	array(
					array(0, 25),
					array(4, 22),
					array(28, 12),
					array(52, 5),
					array(64, 0)				
				);
	$sat = generateWater( 64, $water );	
}

function testGenerateColumn() {

	
	$segment = 	array(
					array(0, 75),
					array(4, 72),
					array(28, 62),
					array(52, 55),
					array(64, 50)
				);
				
	$soil1 = 	array(
					array(0, 25),
					array(4, 22),
					array(28, 12),
					array(52, 5),
					array(64, 0),
					"soiltype"=>"1"
				);
	
	$soil2 = 	array(
					array(0, 0),
					array(4, 0),
					array(28, 0),
					array(52, 0),
					array(64, 0),
					"soiltype"=>"2"
				);
				

	$bottom = 	array(
					array(0, -1),
					array(4, -1),
					array(28, -1),
					array(52, -1),
					array(64, -1),
					"soiltype"=>"10"
				);
	
	$column = array();
	
	for ($i = 0; $i<64; $i++) {
		array_push($column, generateColumn($i+0.5, 75, $segment, $soil1, $soil2, $bottom, $bottom));
	}
	
	echo "<h1>generateColumn</h1>";
	echo "<hr/>";
	
	echo "<table border=1>";
	for ($i=0; $i<count($column); $i++) {
		echo "<tr>";
		echo "<td>" . (count($column) - $i) . "</td>";
		for ($j=0; $j<count($column[$i]); $j++) {
			echo "<td>" . $column[$i][$j] . "</td>";
		}
		echo "</tr>";
	}
	
	echo "</table>";
}

function testGetCellValue() {
	
	$segment = 	array(
					array(0, 75),
					array(4, 72),
					array(28, 62),
					array(52, 55),
					array(64, 50)
				);
				
	$soil1 = 	array(
					array(0, 25),
					array(4, 22),
					array(28, 12),
					array(52, 5),
					array(64, 0),
					"soiltype"=>"1"
				);
	
	$soil2 = 	array(
					array(0, 0),
					array(4, 0),
					array(28, 0),
					array(52, 0),
					array(64, 0),
					"soiltype"=>"2"
				);
				

	$bottom = 	array(
					array(0, -1),
					array(4, -1),
					array(28, -1),
					array(52, -1),
					array(64, -1),
					"soiltype"=>"10"
				);
	
	$test = 	array(
					array(1, 75, 9),
					array(2, 51, 1),
					array(5, 72, 9),
					array(6, 60, 1),
					array(29, 65, 9),
					array(30, 53, 1),
					array(53, 57, 9),
					array(54, 51, 1),
					
					array(1, 25, 1),
					array(2, 1, 2),
					array(5, 22, 1),
					array(6, 10, 2),
					array(29, 15, 1),
					array(30, 3, 2),
					array(53, 7, 1),
					array(54, 1, 2)
				);


	echo "<h1>getCellValue</h1>";
	echo "<table border=1>";
	echo "<tr><th>X</th><th>Y</th><th>Expected Value</th><th>Computed Value</th><th>Pass/Fail</th></tr>";
	for ($i=0; $i<count($test); $i++) {
		$line_seg_idx = findSegment( $test[$i][X], $segment );
		$cv = getCellValue( $test[$i][X], $test[$i][Y], 
					$segment, $soil1, 
					$soil2, $bottom, $bottom );
					
		echo "<tr><td>" . $test[$i][X] . "</td><td>" . $test[$i][Y] . "</td><td>" . $test[$i][2] . "</td><td>" .
						$cv .
						 "</td><td>". ( $cv == $test[$i][2] ? "" : "FAIL") . "</td></tr>";
	}
	echo "</table>";
	
}

function testIsAboveLine() {
	
	$segment = 	array(
					array(0, 25),
					array(4, 22),
					array(28, 12),
					array(52, 5),
					array(64, 0)
				);
	$test = 	array(
					array(1, 25, TRUE),
					array(2, 1, FALSE),
					array(5, 22, TRUE),
					array(6, 10, FALSE),
					array(29, 15, TRUE),
					array(30, 3, FALSE),
					array(53, 7, TRUE),
					array(54, 1, FALSE)
				);

	echo "<h1>isAboveLine</h1>";
	echo "<table border=1>";
	echo "<tr><th>X</th><th>Y</th><th>Expected Value</th><th>Computed Value</th><th>Pass/Fail</th></tr>";
	for ($i=0; $i<count($test); $i++) {
		$line_seg_idx = findSegment( $test[$i][X], $segment );
		$cv = isAboveLine( $test[$i][X], $test[$i][Y], 
					$segment[$line_seg_idx-1][X], $segment[$line_seg_idx-1][Y], 
					$segment[$line_seg_idx][X], $segment[$line_seg_idx][Y] );
					
		echo "<tr><td>" . $test[$i][X] . "</td><td>" . $test[$i][Y] . "</td><td>" . $test[$i][2] . "</td><td>" .
						$cv .
						 "</td><td>". ( $cv == $test[$i][2] ? "" : "FAIL") . "</td></tr>";
	}
	echo "</table>";
	
}

function testFindSegment() {
	
	$segment = 	array(
					array(0, 25),
					array(4, 22),
					array(28, 12),
					array(52, 5),
					array(64, 0)
				);
	

	echo "<h1>findSegment</h1>";
	echo "<table border=1>";
	echo "<tr><th>X</th><th>Expected Value</th><th>Computed Value</th><th>Pass/Fail</th></tr>";
	for ($i=0.5; $i<64; $i+=1.0){
		$ev = 0;
		if ($i <4)
			$ev = 1;
		else if ($i<28)
			$ev = 2;
		else if ($i<52)
			$ev = 3;
		else if ($i<64)
			$ev = 4;
		
		$cv = findSegment( $i, $segment );
		echo "<tr><td>" . $i . "</td><td>" . $ev . "</td><td>" . $cv . "</td><td>". ($ev == $cv ? "" : "FAIL") . "</td></tr>";
	}
	echo "</table>";
	
}


function testGenerateCells() {

	$segment = 	array(
					array(0, 75),
					array(4, 72),
					array(28, 62),
					array(52, 55),
					array(64, 50)
				);
				
	$soil1 = 	array(
					array(0, 25),
					array(4, 22),
					array(28, 12),
					array(52, 5),
					array(64, 0),
					"soiltype"=>"1"
				);
	
	$soil2 = 	array(
					array(0, 0),
					array(4, 0),
					array(28, 0),
					array(52, 0),
					array(64, 0),
					"soiltype"=>"2"
				);
				
	$water =	array(
					array(0, 25),
					array(4, 22),
					array(28, 12),
					array(52, 5),
					array(64, 0)					
				);

	$bottom = 	array(
					array(0, -1),
					array(4, -1),
					array(28, -1),
					array(52, -1),
					array(64, -1),
					"soiltype"=>"10"
				);
		

	$cells = generateCells($segment, $soil1, $soil2, $bottom, $bottom );

/*
	echo "<h1>generateCells</h1>";
	echo "<hr/>";

	echo "<table border=1>";
	for ($i=0; $i<count($cells); $i++) {
		echo "<tr>";
		echo "<td>" . (75 - $i - 0.5) . "</td>";
		for ($j=0; $j<count($cells[$i]); $j++) {
			echo "<td style=\"width: 2em;\">" . $cells[$i][$j] . "</td>";
		}
		echo "</tr>";
	}
	echo "<td>&nbsp;</td>";
	for ($j=1; $j<=count($cells[0]); $j++) {
			echo "<td>" . $j . "</td>";
	}
	
	echo "</table>";
	
	echo "<hr/>";
	*/
	$water_columns = generateWater( 64, $water );
	generateFile( $cells, $water_columns );
}
/*
testFindSegment();
testIsAboveLine();
testGetCellValue();*/
//testGenerateColumn();

//testWater();
//testGenerateCells();
?>